# Generated by Django 3.1.3 on 2020-11-08 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Grad',
                'verbose_name_plural': 'Gradovi',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Županija',
                'verbose_name_plural': 'Županije',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
                ('cover', models.ImageField(upload_to='events/images/', verbose_name='Slika')),
                ('description', models.TextField(verbose_name='Opis')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('start_time', models.TimeField(verbose_name='Vrijeme početka')),
                ('end_time', models.TimeField(verbose_name='Vrijeme završetka')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.city', verbose_name='Grad')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Galerija')),
            ],
            options={
                'verbose_name': 'Događaj',
                'verbose_name_plural': 'Događaji',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.county', verbose_name='Županija'),
        ),
    ]
