# Generated by Django 3.0.4 on 2021-07-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('championships', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=64, verbose_name='Prezime')),
                ('birth_date', models.DateField(verbose_name='Datum rođenja')),
                ('gender', models.CharField(choices=[('M', 'Muško'), ('Z', 'Žensko'), ('O', 'Ostalo')], default='M', max_length=1, verbose_name='Spol')),
                ('driver_image', models.ImageField(default='accounts/profile/default.jpg', upload_to='people/images/', verbose_name='Slika')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('categories', models.ManyToManyField(to='championships.Category', verbose_name='Discipline natjecanja')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City', verbose_name='Grad')),
            ],
            options={
                'verbose_name': 'Vozač',
                'verbose_name_plural': 'Vozači',
            },
        ),
        migrations.CreateModel(
            name='CarDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car', verbose_name='Automobil')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver', verbose_name='Vozač')),
            ],
            options={
                'verbose_name': 'Vozač automobila',
                'verbose_name_plural': 'Vozači automobila',
            },
        ),
        migrations.CreateModel(
            name='DriverSubCategoryPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True, verbose_name='Mjesto')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.Championship')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver', verbose_name='Vozač')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.SubCategory', verbose_name='Podkategorija')),
            ],
            options={
                'verbose_name': 'Pozicija natjecatelja',
                'verbose_name_plural': 'Pozicije natjecatelja',
                'ordering': ['position'],
                'unique_together': {('championship', 'subcategory', 'driver')},
                'index_together': {('championship', 'subcategory', 'driver')},
            },
        ),
    ]
