# Generated by Django 3.0.4 on 2021-07-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardriver',
            unique_together={('car', 'active')},
        ),
    ]
