# Generated by Django 3.1.3 on 2020-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_auto_20201116_1735'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='discipline',
        ),
        migrations.AddField(
            model_name='driver',
            name='discipline',
            field=models.ManyToManyField(null=True, to='championships.Category', verbose_name='Discipline natjecanja'),
        ),
    ]
