# Generated by Django 3.0.4 on 2021-07-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210702_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardriver',
            name='date_deactivated',
            field=models.DateTimeField(null=True, verbose_name='Datum deaktivacije'),
        ),
    ]
