# Generated by Django 3.1.3 on 2020-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20201118_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='discipline',
            field=models.ManyToManyField(to='championships.Category', verbose_name='Discipline natjecanja'),
        ),
    ]
