# Generated by Django 3.1.3 on 2021-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_cardriver_date_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversubcategoryposition',
            name='position_for',
            field=models.CharField(choices=[('ph', 'PH'), ('pir', 'PIR')], default='pir', max_length=32, verbose_name='Bodovanje za'),
            preserve_default=False,
        ),
    ]
