# Generated by Django 3.1.3 on 2021-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driversubcategoryposition_position_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driversubcategoryposition',
            name='position_for',
        ),
        migrations.AddField(
            model_name='driversubcategoryposition',
            name='championship_type',
            field=models.CharField(choices=[('ph', 'PH'), ('pir', 'PIR')], default='pir', max_length=32, verbose_name='Prvenstvo'),
            preserve_default=False,
        ),
    ]
