# Generated by Django 3.0.4 on 2021-07-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20201118_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='discipline',
        ),
        migrations.AlterUniqueTogether(
            name='driversubcategoryposition',
            unique_together={('championship', 'subcategory', 'driver')},
        ),
        migrations.AlterIndexTogether(
            name='driversubcategoryposition',
            index_together={('championship', 'subcategory', 'driver')},
        ),
    ]
