# Generated by Django 3.0.4 on 2021-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20210705_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum rođenja'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Muško'), ('Z', 'Žensko'), ('O', 'Ostalo')], default='M', max_length=1, null=True, verbose_name='Spol'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='driversubcategoryposition',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mjesto'),
        ),
    ]
