# Generated by Django 3.0.4 on 2021-07-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0004_championship_album'),
        ('drivers', '0006_auto_20210701_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driversubcategoryposition',
            unique_together={('championship', 'subcategory', 'driver')},
        ),
        migrations.AlterIndexTogether(
            name='driversubcategoryposition',
            index_together={('championship', 'subcategory', 'driver')},
        ),
    ]
