# Generated by Django 3.1.3 on 2020-11-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=64, verbose_name='Prezime')),
                ('birth_date', models.DateField(verbose_name='Datum rođenja')),
                ('driver_image', models.ImageField(default='accounts/profile/default.jpg', upload_to='people/images/', verbose_name='Slika')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.city', verbose_name='Grad')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osobe',
            },
        ),
    ]
