# Generated by Django 3.1.3 on 2020-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Vozač', 'verbose_name_plural': 'Vozači'},
        ),
        migrations.AddField(
            model_name='driver',
            name='discipline',
            field=models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift')], default=2, verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', 'Muško'), ('Z', 'Žensko'), ('O', 'Ostalo')], default='M', max_length=1, verbose_name='Spol'),
        ),
    ]
