# Generated by Django 3.1.3 on 2020-11-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20201118_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='discipline',
            new_name='disciplines',
        ),
    ]
