# Generated by Django 3.1.3 on 2020-11-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20201118_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='disciplines',
            new_name='categories',
        ),
    ]
