# Generated by Django 3.0.4 on 2021-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20210705_0049'),
        ('gallery', '0002_auto_20210721_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='drivers',
            field=models.ManyToManyField(to='drivers.Driver', verbose_name='Vozači na slici'),
        ),
    ]
