# Generated by Django 3.1.3 on 2020-11-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='accounts/images/default.jpg', max_length=255, upload_to='accounts/images/', verbose_name='Slika'),
        ),
    ]
