# Generated by Django 3.0.4 on 2021-07-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift'), (4, 'General')], default=4, verbose_name='Naziv kategorije')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Tip prvenstva',
                'verbose_name_plural': 'Tipovi prvenstava',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Organizator',
                'verbose_name_plural': 'Organizatori',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64, verbose_name='Naziv kategorije')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivna podkategorija')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.Category')),
            ],
            options={
                'verbose_name': 'Podkategorija',
                'verbose_name_plural': 'Podkategorije',
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
                ('club_count', models.IntegerField(blank=True, null=True, verbose_name='Ukupan broj klubova')),
                ('club_position', models.IntegerField(blank=True, null=True, verbose_name='Pozicija kluba')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('location', models.CharField(max_length=96, verbose_name='Lokacija')),
                ('image', models.ImageField(blank=True, null=True, upload_to='champtionships/images/', verbose_name='Slika')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('albums', models.ManyToManyField(to='gallery.Gallery', verbose_name='Albumi')),
                ('championship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.ChampionshipType')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City', verbose_name='Grad')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.Organizer', verbose_name='Organizator')),
            ],
            options={
                'verbose_name': 'Prvenstvo',
                'verbose_name_plural': 'Prvenstva',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='championship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.ChampionshipType'),
        ),
    ]
