# Generated by Django 3.1.3 on 2020-11-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivna podkategorija'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.city', verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.organizer', verbose_name='Organizator'),
        ),
    ]
