# Generated by Django 3.0.4 on 2021-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_auto_20201116_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorije'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Podkategorija', 'verbose_name_plural': 'Podkategorije'},
        ),
        migrations.AlterField(
            model_name='championship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='champtionships/images/', verbose_name='Slika'),
        ),
    ]
