# Generated by Django 3.0.4 on 2021-07-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_auto_20210702_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='championship_type',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='championship_type',
        ),
        migrations.AddField(
            model_name='championship',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championships.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChampionshipType',
        ),
    ]
