# Generated by Django 3.0.4 on 2021-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_auto_20210702_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift'), (4, 'Općenito')], default=4, verbose_name='Naziv kategorije'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='Općenito', max_length=64, verbose_name='Naziv kategorije'),
        ),
    ]
