# Generated by Django 3.0.4 on 2021-07-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0004_auto_20210702_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['start_date'], 'verbose_name': 'Prvenstvo', 'verbose_name_plural': 'Prvenstva'},
        ),
    ]
