# Generated by Django 3.0.4 on 2021-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0005_auto_20210705_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift'), (4, 'Općenito'), (5, 'OSV')], default=4, verbose_name='Naziv kategorije'),
        ),
    ]
