# Generated by Django 3.1.3 on 2020-11-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('drivers', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Discipline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
                ('level', models.CharField(max_length=64, verbose_name='Razina')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.city', verbose_name='Grad')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Disciplina', to='championships.discipline', verbose_name='Disciplina')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Galerija')),
            ],
            options={
                'verbose_name': 'Prvenstvo',
                'verbose_name_plural': 'Prvenstva',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64, verbose_name='Naziv kategorije')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.championship', verbose_name='Prvenstvo')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDriverPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True, verbose_name='Mjesto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.category', verbose_name='Kategorija')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Vozač')),
            ],
            options={
                'verbose_name': 'Pozicija natjecatelja',
                'verbose_name_plural': 'Pozicije natjecatelja',
                'ordering': ['position'],
                'unique_together': {('category', 'driver')},
                'index_together': {('category', 'driver')},
            },
        ),
    ]
