# Generated by Django 3.1.3 on 2020-11-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20201112_1820'),
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=64, verbose_name='Naziv kategorije')),
            ],
            options={
                'verbose_name': 'Podkategorija',
                'verbose_name_plural': 'Podkategorije',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='championship',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='level',
        ),
        migrations.AddField(
            model_name='championship',
            name='club_position',
            field=models.IntegerField(default=1, verbose_name='Pozicija kluba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championship',
            name='clubs_count',
            field=models.IntegerField(default=1, verbose_name='Ukupan broj klubova'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift'), (4, 'General')], default=1, verbose_name='Naziv kategorije'),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.category', verbose_name='Podkategorija'),
        ),
        migrations.AddField(
            model_name='categorydriverposition',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championships.subcategory', verbose_name='Podkategorija'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categorydriverposition',
            unique_together={('subcategory', 'driver')},
        ),
        migrations.AlterIndexTogether(
            name='categorydriverposition',
            index_together={('subcategory', 'driver')},
        ),
        migrations.RemoveField(
            model_name='categorydriverposition',
            name='category',
        ),
    ]
