# Generated by Django 3.1.3 on 2020-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_auto_20201112_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[(1, 'Brdo'), (2, 'Formula Driver'), (3, 'Drift'), (4, 'General')], default=4, verbose_name='Naziv kategorije'),
        ),
    ]
