# Generated by Django 3.1.3 on 2020-11-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('championships', '0002_auto_20201116_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driversubcategoryposition',
            unique_together={('championship', 'subcategory', 'driver')},
        ),
        migrations.AlterIndexTogether(
            name='driversubcategoryposition',
            index_together={('championship', 'subcategory', 'driver')},
        ),
    ]
