# Generated by Django 3.0.4 on 2021-07-02 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
                ('full_name', models.CharField(max_length=128, verbose_name='Puni naziv')),
                ('city_type', models.IntegerField(choices=[(1, 'Grad'), (2, 'Općina')], verbose_name='Tip mjesta')),
            ],
            options={
                'verbose_name': 'Grad',
                'verbose_name_plural': 'Gradovi',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Županija',
                'verbose_name_plural': 'Županije',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Naziv')),
                ('cover', models.ImageField(upload_to='events/images/', verbose_name='Slika')),
                ('description', models.TextField(verbose_name='Opis')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('start_time', models.TimeField(verbose_name='Vrijeme početka')),
                ('end_time', models.TimeField(verbose_name='Vrijeme završetka')),
                ('albums', models.ManyToManyField(to='gallery.Gallery', verbose_name='Albumi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City', verbose_name='Grad')),
            ],
            options={
                'verbose_name': 'Događaj',
                'verbose_name_plural': 'Događaji',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.County', verbose_name='Županija'),
        ),
    ]
