# Generated by Django 3.0.4 on 2021-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.ManyToManyField(to='gallery.Gallery', verbose_name='Galerija'),
        ),
    ]
