# Generated by Django 3.1.3 on 2020-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201108_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Konjska snaga'),
        ),
    ]
