# Generated by Django 3.0.4 on 2021-07-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
                ('image_url', models.CharField(max_length=2000, verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': 'Proizvođač',
                'verbose_name_plural': 'Proizvođači',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naziv')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Manufacturer', verbose_name='Proizvođač')),
            ],
            options={
                'verbose_name': 'Model automobila',
                'verbose_name_plural': 'Modeli automobila',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_power', models.IntegerField(blank=True, null=True, verbose_name='Konjska snaga')),
                ('capacity', models.IntegerField(choices=[(0, 1000), (1, 1200), (2, 1400), (3, 1600), (4, 1800), (5, 1900), (6, 2000), (7, 2200), (8, 2400), (9, 3000)], null=True, verbose_name='Kubikaža')),
                ('year', models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951)], verbose_name='Godina proizvodnje')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Detalji')),
                ('image', models.ImageField(null=True, upload_to='cars/images/', verbose_name='Slika')),
                ('albums', models.ManyToManyField(to='gallery.Gallery', verbose_name='Albumi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Model', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Automobil',
                'verbose_name_plural': 'Automobili',
            },
        ),
    ]
