# Generated by Django 3.0.4 on 2021-07-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20210701_2326'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver', verbose_name='Vozač'),
            preserve_default=False,
        ),
    ]
