# Generated by Django 3.0.4 on 2021-07-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model__manufacturer__name'], 'verbose_name': 'Automobil', 'verbose_name_plural': 'Automobili'},
        ),
    ]
