# Generated by Django 3.0.4 on 2021-07-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210705_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.CharField(default=1, max_length=3, verbose_name='Kubikaža'),
            preserve_default=False,
        ),
    ]
