# Generated by Django 3.0.4 on 2021-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('cars', '0002_car_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='album',
            field=models.ManyToManyField(to='gallery.Gallery', verbose_name='Galerija'),
        ),
    ]
