# Generated by Django 3.0.4 on 2021-07-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210714_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Proizvođač', 'verbose_name_plural': 'Proizvođači'},
        ),
    ]
